name: 'Post status update to MS Teams'

description: 'Posts a status update to Teams.'

inputs:
  title:
    description: 'The title of the card posted to Teams.'
    required: true
    default: 'GitHub Actions Workflow Status Update'

  workflow-status:
    description: 'The status to report. The values success and failure will result in green and red color indicators (respectively) on the Teams Card. Anything else will result in gray.'
    required: true

  workflow-type:
    description: "The type of workflow. The most common types are Build or Deploy, but the value isn't restricted so anything can be used."
    required: true
    default: Build

  teams-uri:
    description: 'The Teams webhook URI where notifications are sent.'
    required: true

  custom-facts:
    description: 'JSON-parseable string defining a list of objects with name and value to display on the facts table.'
    required: false
    default: null

  custom-actions:
    description: 'JSON-parseable string defining a list of objects with name and uri to include in the list of actions.'
    required: false
    default: null

  timezone:
    description: 'A valid database timezone name, e.g. America/Denver.'
    required: true
    default: 'UTC'

  environment:
    description: "Name of the environment. Won't be included if none."
    required: false
    default: null

runs:
  using: 'node12'
  main: 'dist/index.js'
