const core = require('@actions/core');
const { context } = require('@actions/github');
const { getActions } = require('./actions');

function getGeneralFacts() {
  const includeGeneralFacts = core.getBooleanInput('include-default-facts', {
    required: false
  });

  if (!includeGeneralFacts) {
    return [];
  }

  const status = core.getInput('workflow-status', { required: true });
  const repoUrl = `https://github.com/${process.env.GITHUB_REPOSITORY}`;

  let ref = context.ref;

  if (ref.startsWith('refs/pull/')) {
    // Refs for un-merged pull requests follow the pattern:
    // refs/pull/<pr_number>/merge
    // To create a valid URI we need to remove 'refs/' before adding it to the repository URI
    ref = ref.substring('refs/'.length);
  } else {
    // For all other refs generated by other triggers, append 'tree/'
    ref = `tree/${ref}`;
  }

  const branchUrl = `${repoUrl}/${ref}`;

  const generalFacts = [
    {
      name: 'Event Type: ',
      value: `\`${context.eventName}\``
    },
    {
      name: 'Status: ',
      value: `\`${status}\``
    },
    {
      name: 'Ref: ',
      value: `[${branchUrl}](${branchUrl})`
    }
  ];

  return generalFacts;
}

function getConditionalFacts() {
  const conditionalFacts = [];
  const environment = core.getInput('environment');

  if (environment) {
    conditionalFacts.push({
      name: 'Environment: ',
      value: environment
    });
  }

  return conditionalFacts;
}

function getTheFacts() {
  const customFactsInput = core.getInput('custom-facts');
  const customFactsArray = customFactsInput ? JSON.parse(customFactsInput) : [];

  return [
    ...getGeneralFacts(),
    ...getConditionalFacts(),
    ...(customFactsArray || [])
  ];
}

function getSections() {
  const workflowType = core.getInput('workflow-type', { required: true });
  const workflowStatus = core.getInput('workflow-status', { required: true });
  const timeZone = core.getInput('timezone');
  const section = {
    activityTitle: `${workflowType} ${workflowStatus}`,
    activitySubtitle: new Date().toLocaleString('en-us', {
      timeZone
    }),
    facts: getTheFacts(),
    potentialAction: getActions()
  };

  return [section];
}

module.exports = { getSections };
