##########################################################################################
# Usage:
#   This workflow will run tests against im-open/post-status-to-teams-action.  It
#   can be manually kicked off by providing the action's ref that these tests should
#   be run against.  It is also kicked off as part of the PR process and is a requirement
#   to pass before a PR can be merged into the main branch.
##########################################################################################

name: post-status-to-teams-action-tests
run-name: Test post-status-to-teams-action@${{ inputs.ref || github.event.client_payload.action-ref}}

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ref:
        description: |
          A branch or tag from the post-status-to-teams-action repo.
          The tests in this workflow will run against this ref.
        required: true

env:
  ACTION_REF: ${{ inputs.ref || github.head_ref || github.ref }}

jobs:
  error-condition-tests:
    runs-on: ubuntu-latest

    env:
      MS_TEAMS_URI: ${{ secrets.MS_TEAMS_URI  }}

    steps:
      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                                                    SETUP                                                    '
        run: echo ""

      - name: Setup - Checkout this repo
        uses: actions/checkout@v4 # Required to use the helper scripts

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                                  TEST 1 - MISSING WORKFLOW-STATUS ARG TEST                                  '
        run: echo ""

      - name: 1a - When post-status-to-teams-action is called with a missing workflow-status arg
        id: missing-status
        if: always()
        continue-on-error: true # This is needed because we expect the step to fail but we need it to "pass" in order for the test job to succeed.
        uses: ./
        with:
          teams-uri: ${{ env.MS_TEAMS_URI }}
          workflow-status: ''
          fail-on-error: false

      - name: 1b - Then the outcome should be failure
        if: always()
        run: |
          chmod +x ./test/assert-values-match.sh
          ./test/assert-values-match.sh --name "step outcome" --expected "failure" --actual "${{ steps.missing-status.outcome }}"

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                                     TEST 2 - MISSING TEAMS-URI ARG TEST                                     '
        run: echo ""

      - name: 2a - When post-status-to-teams-action is called with a missing teams-uri arg
        id: missing-teams-uri
        if: always()
        continue-on-error: true # This is needed because we expect the step to fail but we need it to "pass" in order for the test job to succeed.
        uses: ./
        with:
          teams-uri: ''
          workflow-status: 'success'
          fail-on-error: false

      - name: 2b - Then the outcome should be failure
        if: always()
        run: ./test/assert-values-match.sh --name "step outcome" --expected "failure" --actual "${{ steps.missing-teams-uri.outcome }}"

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                             TEST 3 - BAD TEAMS-URI ARG & FAIL-ON-ERROR IS TRUE                              '
        run: echo ""

      - name: 3a - When post-status-to-teams-action is called with bad data and fail-on-error is true
        id: bad-data-and-fail-true
        if: always()
        continue-on-error: true # This is needed because we expect the step to fail but we need it to "pass" in order for the test job to succeed.
        uses: ./
        with:
          teams-uri: 'https://bad-uri-that-does-not-make-sense.com'
          workflow-status: 'success'
          fail-on-error: true

      - name: 3b - Then the outcome should be failure
        if: always()
        run: ./test/assert-values-match.sh --name "step outcome" --expected "failure" --actual "${{ steps.bad-data-and-fail-true.outcome }}"

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                             TEST 4 - BAD TEAMS-URI ARG & FAIL-ON-ERROR IS FALSE                             '
        run: echo ""

      - name: 4a - When post-status-to-teams-action is called with bad data and fail-on-error is false
        id: bad-data-and-fail-false
        if: always()
        continue-on-error: true # This is needed because we expect the step to fail but we need it to "pass" in order for the test job to succeed.
        uses: ./
        with:
          teams-uri: 'https://bad-uri-that-does-not-make-sense.com'
          workflow-status: 'success'
          fail-on-error: false

      - name: 4b - Then the outcome should be success
        if: always()
        run: ./test/assert-values-match.sh --name "step outcome" --expected "success" --actual "${{ steps.bad-data-and-fail-false.outcome }}"

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""

  configured-inputs-test:
    runs-on: ubuntu-latest

    env:
      MS_TEAMS_URI: ${{ secrets.MS_TEAMS_URI }}
      TITLE: 'configured-inputs-test'
      STATUS: 'success'
      COLOR: 'green'
      TYPE: 'Test'
      ENVIRONMENT: 'My test environment'
      CUSTOM_ACTION_NAME: 'Continue test in GitHub'
      WORKFLOW_RUN_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

    steps:
      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                                                    SETUP                                                    '
        run: echo ""

      - name: Setup - Checkout this repo
        uses: actions/checkout@v4 # Required to use the helper scripts

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '              TEST 5 - DEFAULT & CONDITIONAL FACTS & CUSTOM ACTIONS & USES SETS ALL INPUTS TEST              '
        run: echo ""

      - name: 5a - When post-status-to-teams-action is called with all inputs and a 'success' status
        uses: ./
        with:
          # Required - No defaults
          teams-uri: ${{ env.MS_TEAMS_URI }}
          workflow-status: ${{ env.STATUS }}

          # Required Args - Have defaults
          title: ${{ env.TITLE }}
          workflow-type: ${{ env.TYPE }}
          timezone: 'America/Denver'

          # Optional Args
          include-default-facts: true
          environment: ${{ env.ENVIRONMENT }}
          custom-facts: |
            [
              { "name": "**----TEST DETAILS----**", "value": " " },
              { "name": "Repo & branch under test:", "value": "im-open/post-status-to-teams-action@${{ env.ACTION_REF }}" },
              { "name": "Repo containing test:", "value": "${{ github.repository }}" },
              { "name": "Test Run that created this post:", "value": "${{ env.WORKFLOW_RUN_URL }}" },
              { "name": "**----TEST INSTRUCTIONS----**", "value": " " },
              { "name": "- Please review the following criteria for this post then click **${{ env.CUSTOM_ACTION_NAME }}**.\n- On the workflow summary in GitHub, click **Review Deployments** and:\n  - If this post meets the criteria, choose **Approve and deploy**\n  - If this post does not meet the criteria, choose **Reject**", "value": " " },
              { "name": " ", "value": "☐ The main title is _${{ env.TITLE }}_ and the text color is _${{ env.COLOR }}_" },
              { "name": " ", "value": "☐ The first subtitle title is _${{ env.TYPE }} ${{ env.STATUS }}_" },
              { "name": " ", "value": "☐ The timestamp under _${{ env.TYPE }} ${{ env.STATUS }}_ should be close to the post's timestamp in Mountain time" },
              { "name": " ", "value": "☐ The Status is _${{ env.STATUS }}_ and the text color is _${{ env.COLOR }}_" },
              { "name": " ", "value": "☐ The Event Type is _${{ github.event_name }}_" },
              { "name": " ", "value": "☐ The Ref is a link to ${{ github.repository }}/${{ github.ref_name }}" },
              { "name": " ", "value": "☐ The Environment is _${{ env.ENVIRONMENT }}_" },
              { "name": " ", "value": "☐ There is a _View ${{ env.TYPE }} Log_ button that links to the workflow summary" },
              { "name": " ", "value": "☐ There is a _${{ env.CUSTOM_ACTION_NAME}}_ button that also links to the workflow summary" }
            ]
          custom-actions: |
            [
              { "name": "${{ env.CUSTOM_ACTION_NAME }}", "uri": "${{ env.WORKFLOW_RUN_URL }}" }
            ]

      - name: 5b - Then a Purple team member can manually verify the post was created correctly in Teams
        run: |
          echo "Please manually check the 'configured-inputs-test' post in the Platform - Pipeline Builds Teams channel."
          echo "The criteria to check should be listed in the custom facts section at the bottom of the card."

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""

  manually-inspect-configured-inputs-test-post-before-approving:
    runs-on: ubuntu-latest
    needs: configured-inputs-test
    environment: 'manually-inspect-configured-inputs-teams-post'
    steps:
      - run: echo "The all-inputs-and-success-status-test has been verified."

  default-inputs-test:
    runs-on: ubuntu-latest
    needs: manually-inspect-configured-inputs-test-post-before-approving
    if: always()
    env:
      MS_TEAMS_URI: ${{ secrets.MS_TEAMS_URI }}
      TITLE: 'GitHub Actions Workflow Status Update'
      STATUS: 'failure'
      COLOR: 'red'
      TYPE: 'Build'
      CUSTOM_ACTION_NAME: 'Continue test in GitHub'
      WORKFLOW_RUN_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

    steps:
      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '                                                    SETUP                                                    '
        run: echo ""

      - name: Setup - Checkout this repo
        uses: actions/checkout@v4 # Required to use the helper scripts

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""
      - name: '               TEST 6 - DEFAULT INPUTS AND DOES NOT INCLUDE DEFAULT OR CONDITIONAL FACTS TEST                '
        run: echo ""

      - name: 6a - When post-status-to-teams-action is called with default inputs and a 'failure' status
        uses: ./
        with:
          teams-uri: ${{ env.MS_TEAMS_URI }}
          workflow-status: ${{ env.STATUS }}
          include-default-facts: false
          custom-facts: |
            [
              { "name": "**----TEST DETAILS----**", "value": " " },
              { "name": "Repo & branch under test:", "value": "im-open/post-status-to-teams-action@${{ env.ACTION_REF }}" },
              { "name": "Repo containing test:", "value": "${{ github.repository }}" },
              { "name": "Test Run that created this post:", "value": "${{ env.WORKFLOW_RUN_URL }}" },
              { "name": "**----TEST INSTRUCTIONS----**", "value": " " },
              { "name": "- Please review the following criteria for this post then click **${{ env.CUSTOM_ACTION_NAME }}**.\n- On the workflow summary in GitHub, click **Review Deployments** and:\n - If this post meets the criteria, choose **Approve and deploy**\n  -  If this post does not meet the criteria, choose **Reject**", "value": " " },
              { "name": " ", "value": "☐ The main title is _${{ env.TITLE }}_ and the text color is _${{ env.COLOR }}_" },
              { "name": " ", "value": "☐ The first subtitle title is _${{ env.TYPE }} ${{ env.STATUS }}_" },
              { "name": " ", "value": "☐ The timestamp under _${{ env.TYPE }} ${{ env.STATUS }}_ should be close to the post's timestamp but in UTC" },
              { "name": " ", "value": "☐ The Status is _${{ env.STATUS }}_ and the text color is _${{ env.COLOR }}_" },
              { "name": " ", "value": "☐ There should not be an Event Type, Ref or Environment fact" },
              { "name": " ", "value": "☐ There is a _View ${{ env.TYPE }} Log_ button that links to the workflow summary" },
              { "name": " ", "value": "☐ There is a _${{ env.CUSTOM_ACTION_NAME}}_ that also links to the workflow summary" }
            ]
          custom-actions: |
            [
              { "name": "${{ env.CUSTOM_ACTION_NAME }}", "uri": "${{ env.WORKFLOW_RUN_URL }}" }
            ]

      - name: 6b - Then a Purple member can manually verify the post was created correctly in Teams
        run: |
          echo "Please manually check the 'GitHub Actions Workflow Status Update' post in the Platform - Pipeline Builds Teams channel."
          echo "The criteria to check should be listed in the custom facts section at the bottom of the card."

      - name: '-------------------------------------------------------------------------------------------------------------'
        run: echo ""

  manually-inspect-default-inputs-test-post-before-approving:
    runs-on: ubuntu-latest
    needs: default-inputs-test
    if: always()
    environment: 'manually-inspect-default-inputs-teams-post'
    steps:
      - run: echo "The default-inputs-test has been verified."
