name: Test Pushing to Teams on Pull Request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Successful Build Notification
        uses: ./
        with:
          title: Successfully built the thing
          workflow-status: success
          workflow-type: Build
          teams-uri: ${{ secrets.MS_TEAMS_URI }}
          timezone: America/Denver
